-- Inserindo usuários iniciais
INSERT INTO usuarios (id, nome, email, senha, idade, role) VALUES
(UUID_TO_BIN(UUID()), 'Admin Sistema', 'admin@biblioteca.com', '$2a$10$YL3GZO3zHHOVw3YlL0.1/OVhp1oPY0zyY5.6RbiMqoX3re8xAXqxq', 35, 'ADMIN'),
(UUID_TO_BIN(UUID()), 'Maria Silva', 'maria@email.com', '$2a$10$YL3GZO3zHHOVw3YlL0.1/OVhp1oPY0zyY5.6RbiMqoX3re8xAXqxq', 28, 'COMUM'),
(UUID_TO_BIN(UUID()), 'João Santos', 'joao@email.com', '$2a$10$YL3GZO3zHHOVw3YlL0.1/OVhp1oPY0zyY5.6RbiMqoX3re8xAXqxq', 42, 'COMUM');

-- Inserindo livros iniciais com apenas os nomes dos arquivos
INSERT INTO livros (id, titulo, autor, genero, capa_foto, disponivel_locacao, classificacao_etaria, estado_conservacao, sinopse) VALUES
(UUID_TO_BIN(UUID()), 'A Guerra dos Tronos', 'George R. R. Martin', 'FICCAO', 'aguerradostronos.jpg', true, 'DEZOITO_ANOS', 'BOM', 'Em um reino onde as estações duram anos, uma batalha épica pelo trono de ferro está prestes a começar. Intrigas políticas, segredos obscuros e uma antiga ameaça convergem nesta saga fantástica.'),
(UUID_TO_BIN(UUID()), 'Harry Potter e a Ordem da Fênix', 'J.K. Rowling', 'FICCAO', 'aOrderDaFenix.jpg', false, 'DOZE_ANOS', 'OTIMO', 'Harry retorna para seu quinto ano em Hogwarts, enfrentando a negação do Ministério da Magia sobre o retorno de Voldemort e formando um grupo secreto para preparar os estudantes para o perigo iminente.'),
(UUID_TO_BIN(UUID()), 'Clean Code', 'Robert C. Martin', 'TECNICO', 'cleancode.jpg', true, 'LIVRE', 'BOM', 'Um guia prático para produzir código limpo e manutenível. O autor apresenta princípios, padrões e práticas para criar software profissional de qualidade.'),
(UUID_TO_BIN(UUID()), 'Eragon', 'Christopher Paolini', 'FICCAO', 'eragonPaolini.jpg', true, 'DOZE_ANOS', 'BOM', 'A jornada épica de um jovem fazendeiro que descobre um ovo de dragão misterioso, levando-o a uma aventura que mudará para sempre o destino de sua terra.'),
(UUID_TO_BIN(UUID()), 'George Martin: O Começo', 'James Hibberd', 'NAO_FICCAO', 'georgemartinOcomeco.jpg', true, 'LIVRE', 'OTIMO', 'Uma biografia detalhada sobre a vida e carreira do autor de As Crônicas de Gelo e Fogo, revelando sua jornada desde os primeiros contos até se tornar um dos escritores mais influentes da fantasia moderna.'),
(UUID_TO_BIN(UUID()), 'Harry Potter e a Câmara Secreta', 'J.K. Rowling', 'FICCAO', 'harrypotterEacamarasecreta.jpg', true, 'DOZE_ANOS', 'BOM', 'No segundo ano em Hogwarts, Harry enfrenta um mistério ainda mais perigoso quando alunos começam a ser petrificados e uma mensagem sinistra aparece nas paredes do castelo.'),
(UUID_TO_BIN(UUID()), 'Matéria Escura', 'Blake Crouch', 'FICCAO', 'materiaescura.jpg', true, 'DEZESSEIS_ANOS', 'BOM', 'Um thriller científico que explora realidades alternativas quando um físico se vê em uma versão diferente de sua vida, questionando todas as suas escolhas e a própria natureza da realidade.'),
(UUID_TO_BIN(UUID()), 'Padrões de Projeto', 'Erich Gamma', 'TECNICO', 'padroesdeprojeto.jpg', true, 'LIVRE', 'BOM', 'Uma referência essencial sobre padrões de design de software, apresentando soluções reutilizáveis para problemas comuns no desenvolvimento de software orientado a objetos.'),
(UUID_TO_BIN(UUID()), 'Refatoração', 'Martin Fowler', 'TECNICO', 'refatoracao.jpg', true, 'LIVRE', 'OTIMO', 'Um guia completo sobre como melhorar o design de código existente, apresentando técnicas sistemáticas para aprimorar a estrutura de software sem alterar seu comportamento externo.');
